### ISSUE TITLE
The status of this SDK?

### ISSUE THREAD

**Issue by TokenChingy** [kuzzleio/sdk-python3#4]
Just curious as the the status of this SDK.

**Comment by Aschen** [comment]
Hi @TokenChingy ,

This SDK is in standby since we abandoned SWIG template engine for building the SDKs.  
We want to entirely rebuild this SDK in native Python code, it's on our [Product Roadmap](https://trello.com/c/hgcUpFC1/44-native-python-sdk), don't hesitate to vote if you want this feature to be released!

Honestly we didn't have much time since we have many other projects to work on. We are either waiting for a paid customer that want to use the Python SDK or a strong demand from the community.

**Comment by TokenChingy** [comment]
Could someone like me contribute and get it going?

**Comment by Aschen** [comment]
Since we didn't start to work on this SDK, even the fundamental building blocks have to be made such as the `Kuzzle` object, the protocol abstraction and at least the `WebSocket` implementation or the `query` method.  
We also have to setup at least these element but also the documentation framework and the functional tests so it will be difficult to integrate external contribution for now :/

There is two other possibilities:
  - you can develop a community SDK (like the [Dart SDK](https://github.com/prijindal/kuzzle_dart)) and try to follow or not our other SDK architecture
  - If you need this SDK for a professional project with a paid support, we can prioritize it's developmen

**Comment by scottinet** [comment]
We'll eventually develop a python sdk. In the meantime, I'm closing this issue.
